checks:
  php: true
filter:
  excluded_paths:
      - tests/*
build:
  environment:
    php:
      version: 7.0.20
  dependencies:
    before:
      - composer require phpunit/phpunit ^6.4
  tests:
    override:
      -
        command: vendor/bin/phpunit
          coverage:
            file: tests/report/clover.xml
              format: php-clover
